name: estacionaudec
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  http: ^1.0.0
  google_maps_flutter: ^2.5.0
  flutter_snake_navigationbar: ^0.6.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  timezone: ^0.8.0
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconapp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets\images\arco_udec.png
    - assets\images\campanil.jpg


